### ISSUE TITLE
fftw3_mpi

### ISSUE THREAD

**Issue by paugier** [conda-forge/fluidfft-feedstock#3]
For the builds using MPI, we should now be able to use fftw and fftw_mpi: 

https://github.com/conda-forge/fftw-feedstock/pull/52

Something that may not be so easy: the configuration file has to be different with and without MPI.

**Comment by CyrilleBonamy** [comment]
fttw_mpi support add in https://github.com/conda-forge/fluidfft-feedstock/pull/4
