### ISSUE TITLE
This package (cf binary) likley has to be GPL licensed due to linking against FFTW

### ISSUE THREAD

**Issue by moorepants** [conda-forge/fluidfft-feedstock#9]
We came to the conclusion here:

https://github.com/conda-forge/pyshtools-feedstock/issues/3

that the Conda Forge binaries that link against FFTW have to be GPL licensed. This would likely the case for this package too.

**Comment by ashwinvis** [comment]
Thanks for pointing that out. It is actually CeCILL licensed which is [compatible with GPL](https://www.gnu.org/licenses/license-list.html#CeCILL). It is regarded as a license with copyleft characteristics. The following excerpt is relevant:

> 
> 
> 5.3.2 DISTRIBUTION OF MODIFIED SOFTWARE
> 
> When the Licensee makes a Contribution to the Software, the terms and conditions for the distribution of the resulting Modified Software become subject to all the provisions of this Agreement.
> 
> The Licensee is authorized to distribute the Modified Software, in source code or object code form, provided that said distribution complies with all the provisions of the Agreement and is accompanied by:
> 
>     a copy of the Agreement,
> 
>     a notice relating to the limitation of both the Licensor's warranty and liability as set forth in Articles 8 and 9,
> 
> and, in the event that only the object code of the Modified Software is redistributed,
> 
>     a note stating the conditions of effective access to the full source code of the Modified Software for a period of at least three years from the distribution of the Modified Software, it being understood that the additional acquisition cost of the source code shall not exceed the cost of the data transfer.
> 
> 5.3.3 DISTRIBUTION OF EXTERNAL MODULES
> 
> When the Licensee has developed an External Module, the terms and conditions of this Agreement do not apply to said External Module, that may be distributed under a separate license agreement.
> 5.3.4 COMPATIBILITY WITH OTHER LICENSES
> 
> The Licensee can include a code that is subject to the provisions of one of the versions of the GNU GPL, GNU Affero GPL and/or EUPL in the Modified or unmodified Software, and distribute that entire code under the terms of the same version of the GNU GPL, GNU Affero GPL and/or EUPL.
> 
> The Licensee can include the Modified or unmodified Software in a code that is subject to the provisions of one of the versions of the GNU GPL, GNU Affero GPL and/or EUPL and distribute that entire code under the terms of the same version of the GNU GPL, GNU Affero GPL and/or EUPL.
> 

The CeCILL-B package license was a typo, and is being rectified in #11. Do you think this suffices?

**Comment by moorepants** [comment]
I'm not sure. I haven't thought about it in a while. I did open this issue to try to articulate things:

https://github.com/conda-forge/conda-forge.github.io/issues/1065

There is a confusing nuance about the dynamic linking that I never came to a solid conclusion on and it doesn't seem like there is much energy to try to address it.
